
package com.ecodeup.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ServiciowebImplService", targetNamespace = "http://ws.ecodeup.com/", wsdlLocation = "http://localhost:1212/WS/Servicioweb?wsdl")
public class ServiciowebImplService
    extends Service
{

    private final static URL SERVICIOWEBIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException SERVICIOWEBIMPLSERVICE_EXCEPTION;
    private final static QName SERVICIOWEBIMPLSERVICE_QNAME = new QName("http://ws.ecodeup.com/", "ServiciowebImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:1212/WS/Servicioweb?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICIOWEBIMPLSERVICE_WSDL_LOCATION = url;
        SERVICIOWEBIMPLSERVICE_EXCEPTION = e;
    }

    public ServiciowebImplService() {
        super(__getWsdlLocation(), SERVICIOWEBIMPLSERVICE_QNAME);
    }

    public ServiciowebImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICIOWEBIMPLSERVICE_QNAME, features);
    }

    public ServiciowebImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICIOWEBIMPLSERVICE_QNAME);
    }

    public ServiciowebImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICIOWEBIMPLSERVICE_QNAME, features);
    }

    public ServiciowebImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServiciowebImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Servicioweb
     */
    @WebEndpoint(name = "ServiciowebImplPort")
    public Servicioweb getServiciowebImplPort() {
        return super.getPort(new QName("http://ws.ecodeup.com/", "ServiciowebImplPort"), Servicioweb.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Servicioweb
     */
    @WebEndpoint(name = "ServiciowebImplPort")
    public Servicioweb getServiciowebImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.ecodeup.com/", "ServiciowebImplPort"), Servicioweb.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICIOWEBIMPLSERVICE_EXCEPTION!= null) {
            throw SERVICIOWEBIMPLSERVICE_EXCEPTION;
        }
        return SERVICIOWEBIMPLSERVICE_WSDL_LOCATION;
    }

}
